---
driver:
  name: docker

driver_config:
  require_chef_omnibus: false
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver_config:
      provision_command:
        - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -d /tmp/vagrant-cache/vagrant_omnibus/
  - name: centos-7.1
    driver_config:
      provision_command:
        - curl -L https://www.opscode.com/chef/install.sh | bash -s -- -d /tmp/vagrant-cache/vagrant_omnibus/
suites:
  - name: create
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fake-cookbook::append]
    attributes:
      ssh_known_hosts:
        files:
          -
            file: /tmp/foo
            entries:
              -
               host: '[host.with.port.com:2222]'
               type: ecdsa-sha2-nistp256
               key:  'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHLTo5p/y4JpXvY8rqHYvH4eisabTqpS+MJTBSD08ypiocl70kB2wjkLZmEme5WkLMlq9HtvwHx53JLr+dkjWQI='

              -
               host: 'github.com,192.30.252.129'
               type: rsa
               key:  'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='

  - name: append
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[fake-cookbook::append]
    attributes:
      ssh_known_hosts:
        files:
          -
            file: /tmp/foo
            append: true
            entries:
              -
               host: '[host.with.port.com:2222]'
               type: ecdsa-sha2-nistp256
               key:  'AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHLTo5p/y4JpXvY8rqHYvH4eisabTqpS+MJTBSD08ypiocl70kB2wjkLZmEme5WkLMlq9HtvwHx53JLr+dkjWQI='

              -
               host: 'github.com,192.30.252.129'
               type: rsa
               key:  'AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
