name 'ssh_user_known_hosts'
maintainer 'Barney Hanlon'
maintainer_email 'bhanlon@inviqa.com'
license 'all_rights'
description 'Installs/Configures ssh-known-hosts for users'
long_description 'Installs/Configures ssh-known-hosts'
version '0.2.0'
